/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carskit.gui;

import java.io.BufferedReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import carskit.main.CARS;
import static carskit.main.CARS.WorkingPath;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.table.DefaultTableModel;
import happy.coding.io.Logs;

/**
 *
 * @author sihc
 */
public class CARSKit_Form extends javax.swing.JFrame {

    /**
     * Creates new form CARSKit_FORM
     */
    public CARSKit_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedChoossen = new javax.swing.JTabbedPane();
        jPanelConfig = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        data_path = new javax.swing.JTextField();
        jButton_browser_data = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        config_path = new javax.swing.JTextField();
        jButton_browser_config = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_data = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanelAlgorithm = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jButtonRunGlobalAVG = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButtonRunUserAVG = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButtonRunItemAVG = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButtonRunContextAVG = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButtonRunUserItemAVG = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButtonRunUserContextAVG = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButtonRunItemContextAVG = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jButtonRunUserKNN = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jButtonRunItemKNN = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jButtonRunSlopOne = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jButtonRunBiasedMF = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jButtonRunPMF = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jButtonRunBPMF = new javax.swing.JButton();
        jPanel37 = new javax.swing.JPanel();
        jButtonRunNMF = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jButtonRunSVDPP = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButtonRunBPR = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButtonRunSLIM = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jButtonRunLRMF = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jButtonRunRankALS = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jButtonRunRankSGD = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel27 = new javax.swing.JPanel();
        jButtonRunItemSplitting = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jButtonRunUserSplitting = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jButtonRunUISplitting = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel30 = new javax.swing.JPanel();
        jButtonRunTF = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel31 = new javax.swing.JPanel();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jPanel38 = new javax.swing.JPanel();
        jButtonRunCAMF_C = new javax.swing.JButton();
        jPanel33 = new javax.swing.JPanel();
        jButtonRunCAMF_CI = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jButtonRunCAMF_CU = new javax.swing.JButton();
        jPanel39 = new javax.swing.JPanel();
        jButtonRunCAMF_CUCI = new javax.swing.JButton();
        jPanel40 = new javax.swing.JPanel();
        jButtonRunCAMF_ICS = new javax.swing.JButton();
        jPanel41 = new javax.swing.JPanel();
        jButtonRunCAMF_LCS = new javax.swing.JButton();
        jPanel42 = new javax.swing.JPanel();
        jButtonRunCAMF_MCS = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel43 = new javax.swing.JPanel();
        jButtonRunCSLIM_C = new javax.swing.JButton();
        jPanel44 = new javax.swing.JPanel();
        jButtonRunCSLIM_CU = new javax.swing.JButton();
        jPanel45 = new javax.swing.JPanel();
        jButtonRunCSLIM_CI = new javax.swing.JButton();
        jPanel46 = new javax.swing.JPanel();
        jButtonRunCSLIM_CUCI = new javax.swing.JButton();
        jPanel48 = new javax.swing.JPanel();
        jButtonRunCSLIM_ICS = new javax.swing.JButton();
        jPanel49 = new javax.swing.JPanel();
        jButtonRunCSLIM_LCS = new javax.swing.JButton();
        jPanel50 = new javax.swing.JPanel();
        jButtonRunCSLIM_MCS = new javax.swing.JButton();
        jPanel47 = new javax.swing.JPanel();
        jButtonRunGCSLIM_CC = new javax.swing.JButton();
        jPanel51 = new javax.swing.JPanel();
        jButtonRunGCSLIM_ICS = new javax.swing.JButton();
        jPanel52 = new javax.swing.JPanel();
        jButtonRunGCSLIM_LCS = new javax.swing.JButton();
        jPanel53 = new javax.swing.JPanel();
        jButtonRunGCSLIM_MCS = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        jButtonRunFM = new javax.swing.JButton();
        jPanelVariable = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelConfig.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("File data");

        data_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_pathActionPerformed(evt);
            }
        });

        jButton_browser_data.setText("Browser");
        jButton_browser_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browser_dataActionPerformed(evt);
            }
        });

        jLabel3.setText("File config");

        config_path.setText("./setting.conf");
        config_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                config_pathActionPerformed(evt);
            }
        });

        jButton_browser_config.setText("Browser");
        jButton_browser_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browser_configActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable_data);

        jLabel2.setText("Data");

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConfigLayout = new javax.swing.GroupLayout(jPanelConfig);
        jPanelConfig.setLayout(jPanelConfigLayout);
        jPanelConfigLayout.setHorizontalGroup(
            jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfigLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConfigLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(jPanelConfigLayout.createSequentialGroup()
                            .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(config_path)
                                .addComponent(data_path, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_browser_config)
                                .addComponent(jButton_browser_data)))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanelConfigLayout.setVerticalGroup(
            jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfigLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(config_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_browser_config))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_browser_data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTabbedChoossen.addTab("Config", jPanelConfig);

        jPanelAlgorithm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonRunGlobalAVG.setText("Run");
        jButtonRunGlobalAVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunGlobalAVGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunGlobalAVG)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButtonRunGlobalAVG)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Global AVG", jPanel10);

        jButtonRunUserAVG.setText("Run");
        jButtonRunUserAVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunUserAVGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunUserAVG)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButtonRunUserAVG)
                .addContainerGap())
        );

        jTabbedPane3.addTab("User AVG", jPanel11);

        jButtonRunItemAVG.setText("Run");
        jButtonRunItemAVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunItemAVGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunItemAVG)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButtonRunItemAVG)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Item AVG", jPanel12);

        jButtonRunContextAVG.setText("Run");
        jButtonRunContextAVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunContextAVGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunContextAVG)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButtonRunContextAVG)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Context AVG", jPanel13);

        jButtonRunUserItemAVG.setText("Run");
        jButtonRunUserItemAVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunUserItemAVGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunUserItemAVG)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButtonRunUserItemAVG)
                .addContainerGap())
        );

        jTabbedPane3.addTab("User Item AVG", jPanel14);

        jButtonRunUserContextAVG.setText("Run");
        jButtonRunUserContextAVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunUserContextAVGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunUserContextAVG)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButtonRunUserContextAVG)
                .addContainerGap())
        );

        jTabbedPane3.addTab("User Context AVG", jPanel15);

        jButtonRunItemContextAVG.setText("Run");
        jButtonRunItemContextAVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunItemContextAVGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunItemContextAVG)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButtonRunItemContextAVG)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Item Context AVG", jPanel16);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("Average", jPanel1);

        jTabbedPane5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonRunUserKNN.setText("Run");
        jButtonRunUserKNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunUserKNNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunUserKNN)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButtonRunUserKNN)
                .addContainerGap())
        );

        jTabbedPane5.addTab("User KNN", jPanel18);

        jButtonRunItemKNN.setText("Run");
        jButtonRunItemKNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunItemKNNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunItemKNN)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButtonRunItemKNN)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Item KNN", jPanel19);

        jButtonRunSlopOne.setText("Run");
        jButtonRunSlopOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunSlopOneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunSlopOne)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButtonRunSlopOne)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Slope One", jPanel20);

        jButtonRunBiasedMF.setText("Run");
        jButtonRunBiasedMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunBiasedMFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunBiasedMF)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButtonRunBiasedMF)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Biased MF", jPanel21);

        jButtonRunPMF.setText("Run");
        jButtonRunPMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunPMFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunPMF)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButtonRunPMF)
                .addContainerGap())
        );

        jTabbedPane5.addTab("PMF", jPanel22);

        jButtonRunBPMF.setText("Run");
        jButtonRunBPMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunBPMFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunBPMF)
                .addContainerGap())
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButtonRunBPMF)
                .addContainerGap())
        );

        jTabbedPane5.addTab("BPMF", jPanel36);

        jButtonRunNMF.setText("Run");
        jButtonRunNMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunNMFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunNMF)
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButtonRunNMF)
                .addContainerGap())
        );

        jTabbedPane5.addTab("NMF", jPanel37);

        jButtonRunSVDPP.setText("Run");
        jButtonRunSVDPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunSVDPPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunSVDPP)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButtonRunSVDPP)
                .addContainerGap())
        );

        jTabbedPane5.addTab("SVD++", jPanel23);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        jTabbedPane1.addTab("Collaborative Filtering", jPanel4);

        jTabbedPane6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonRunBPR.setText("Run");
        jButtonRunBPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunBPRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunBPR)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jButtonRunBPR)
                .addContainerGap())
        );

        jTabbedPane6.addTab("BPR", jPanel3);

        jButtonRunSLIM.setText("Run");
        jButtonRunSLIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunSLIMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunSLIM)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jButtonRunSLIM)
                .addContainerGap())
        );

        jTabbedPane6.addTab("SLIM", jPanel17);

        jButtonRunLRMF.setText("Run");
        jButtonRunLRMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunLRMFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunLRMF)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jButtonRunLRMF)
                .addContainerGap())
        );

        jTabbedPane6.addTab("LRMF", jPanel24);

        jButtonRunRankALS.setText("Run");
        jButtonRunRankALS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunRankALSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunRankALS)
                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jButtonRunRankALS)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Rank ALS", jPanel25);

        jButtonRunRankSGD.setText("Run");
        jButtonRunRankSGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunRankSGDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunRankSGD)
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jButtonRunRankSGD)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Rank SGD", jPanel26);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );

        jTabbedPane1.addTab("Raking", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelAlgorithmLayout = new javax.swing.GroupLayout(jPanelAlgorithm);
        jPanelAlgorithm.setLayout(jPanelAlgorithmLayout);
        jPanelAlgorithmLayout.setHorizontalGroup(
            jPanelAlgorithmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgorithmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlgorithmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAlgorithmLayout.setVerticalGroup(
            jPanelAlgorithmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgorithmLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedChoossen.addTab("Baseline Algorithms", jPanelAlgorithm);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonRunItemSplitting.setText("Run");
        jButtonRunItemSplitting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunItemSplittingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunItemSplitting)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jButtonRunItemSplitting)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Item Splitting", jPanel27);

        jButtonRunUserSplitting.setText("Run");
        jButtonRunUserSplitting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunUserSplittingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunUserSplitting)
                .addContainerGap())
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jButtonRunUserSplitting)
                .addContainerGap())
        );

        jTabbedPane4.addTab("User Splitting", jPanel28);

        jButtonRunUISplitting.setText("Run");
        jButtonRunUISplitting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunUISplittingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunUISplitting)
                .addContainerGap())
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jButtonRunUISplitting)
                .addContainerGap())
        );

        jTabbedPane4.addTab("UI Splitting", jPanel29);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        jTabbedPane2.addTab("Transformation", jPanel7);

        jTabbedPane7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonRunTF.setText("Run");
        jButtonRunTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunTF)
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jButtonRunTF)
                .addContainerGap())
        );

        jTabbedPane7.addTab("Tensor Factorization", jPanel30);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );

        jTabbedPane2.addTab("Adaptation Independent", jPanel8);

        jTabbedPane8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonRunCAMF_C.setText("Run");
        jButtonRunCAMF_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCAMF_CActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel38Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_C)
                .addContainerGap())
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel38Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_C))
        );

        jTabbedPane9.addTab("CAMF_C", jPanel38);

        jButtonRunCAMF_CI.setText("Run");
        jButtonRunCAMF_CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCAMF_CIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_CI)
                .addContainerGap())
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_CI))
        );

        jTabbedPane9.addTab("CAMF_CI", jPanel33);

        jButtonRunCAMF_CU.setText("Run");
        jButtonRunCAMF_CU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCAMF_CUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_CU)
                .addContainerGap())
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_CU))
        );

        jTabbedPane9.addTab("CAMF_CU", jPanel34);

        jButtonRunCAMF_CUCI.setText("Run");
        jButtonRunCAMF_CUCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCAMF_CUCIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_CUCI)
                .addContainerGap())
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_CUCI))
        );

        jTabbedPane9.addTab("CAMF_CUCI", jPanel39);

        jButtonRunCAMF_ICS.setText("Run");
        jButtonRunCAMF_ICS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCAMF_ICSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_ICS)
                .addContainerGap())
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_ICS))
        );

        jTabbedPane9.addTab("CAMF_ICS", jPanel40);

        jButtonRunCAMF_LCS.setText("Run");
        jButtonRunCAMF_LCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCAMF_LCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel41Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_LCS)
                .addContainerGap())
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel41Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_LCS))
        );

        jTabbedPane9.addTab("CAMF_LCS", jPanel41);

        jButtonRunCAMF_MCS.setText("Run");
        jButtonRunCAMF_MCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCAMF_MCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                .addGap(0, 778, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_MCS))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(jButtonRunCAMF_MCS))
        );

        jTabbedPane9.addTab("CAMF_MCS", jPanel42);

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane9)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addComponent(jTabbedPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("Context Aware Matrix Factorization", jPanel31);

        jButtonRunCSLIM_C.setText("Run");
        jButtonRunCSLIM_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCSLIM_CActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_C)
                .addContainerGap())
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_C))
        );

        jTabbedPane10.addTab("CSLIM_C", jPanel43);

        jButtonRunCSLIM_CU.setText("Run");
        jButtonRunCSLIM_CU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCSLIM_CUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel44Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_CU)
                .addContainerGap())
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel44Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_CU))
        );

        jTabbedPane10.addTab("CSLIM_CU", jPanel44);

        jButtonRunCSLIM_CI.setText("Run");
        jButtonRunCSLIM_CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCSLIM_CIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel45Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_CI)
                .addContainerGap())
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel45Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_CI))
        );

        jTabbedPane10.addTab("CSLIM_CI", jPanel45);

        jButtonRunCSLIM_CUCI.setText("Run");
        jButtonRunCSLIM_CUCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCSLIM_CUCIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel46Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_CUCI)
                .addContainerGap())
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel46Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_CUCI))
        );

        jTabbedPane10.addTab("CSLIM_CUCI", jPanel46);

        jButtonRunCSLIM_ICS.setText("Run");
        jButtonRunCSLIM_ICS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCSLIM_ICSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel48Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_ICS)
                .addContainerGap())
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel48Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_ICS))
        );

        jTabbedPane10.addTab("CSLIM_ICS", jPanel48);

        jButtonRunCSLIM_LCS.setText("Run");
        jButtonRunCSLIM_LCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCSLIM_LCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel49Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_LCS)
                .addContainerGap())
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel49Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_LCS))
        );

        jTabbedPane10.addTab("CSLIM_LCS", jPanel49);

        jButtonRunCSLIM_MCS.setText("Run");
        jButtonRunCSLIM_MCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCSLIM_MCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel50Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_MCS)
                .addContainerGap())
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel50Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunCSLIM_MCS))
        );

        jTabbedPane10.addTab("CSLIM_MCS", jPanel50);

        jButtonRunGCSLIM_CC.setText("Run");
        jButtonRunGCSLIM_CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunGCSLIM_CCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel47Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunGCSLIM_CC)
                .addContainerGap())
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel47Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunGCSLIM_CC))
        );

        jTabbedPane10.addTab("GCSLIM_CC", jPanel47);

        jButtonRunGCSLIM_ICS.setText("Run");
        jButtonRunGCSLIM_ICS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunGCSLIM_ICSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel51Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunGCSLIM_ICS)
                .addContainerGap())
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel51Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunGCSLIM_ICS))
        );

        jTabbedPane10.addTab("GCSLIM_ICS", jPanel51);

        jButtonRunGCSLIM_LCS.setText("Run");
        jButtonRunGCSLIM_LCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunGCSLIM_LCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel52Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunGCSLIM_LCS)
                .addContainerGap())
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel52Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunGCSLIM_LCS))
        );

        jTabbedPane10.addTab("GCSLIM_LCS", jPanel52);

        jButtonRunGCSLIM_MCS.setText("Run");
        jButtonRunGCSLIM_MCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunGCSLIM_MCSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel53Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jButtonRunGCSLIM_MCS)
                .addContainerGap())
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel53Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jButtonRunGCSLIM_MCS))
        );

        jTabbedPane10.addTab("GCSLIM_MCS", jPanel53);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane10)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, Short.MAX_VALUE)
        );

        jTabbedPane8.addTab("Contextual SLIM Recommendation Algorithms", jPanel32);

        jButtonRunFM.setText("Run");
        jButtonRunFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunFMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35Layout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(jButtonRunFM)
                .addContainerGap())
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jButtonRunFM)
                .addContainerGap())
        );

        jTabbedPane8.addTab("Factorization machines", jPanel35);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane8)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jTabbedPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Adaptation Dependent", jPanel9);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        jTabbedChoossen.addTab("CARS Algorithms", jPanel6);

        jPanelVariable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelVariableLayout = new javax.swing.GroupLayout(jPanelVariable);
        jPanelVariable.setLayout(jPanelVariableLayout);
        jPanelVariableLayout.setHorizontalGroup(
            jPanelVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelVariableLayout.setVerticalGroup(
            jPanelVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedChoossen)
                    .addComponent(jPanelVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jTabbedChoossen, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_pathActionPerformed
        try {
            show_data_table();
        } catch (IOException ex) {
            Logger.getLogger(CARSKit_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_data_pathActionPerformed

    private void jButton_browser_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browser_dataActionPerformed
        // TODO add your handling code here:
        OpenFile f = new OpenFile();
        try {
            f.openFile();
            data_path.setText(f.path);
            show_data_table();
        } catch (IOException ex) {
            Logger.getLogger(CARSKit_Form.class.getName()).log(Level.SEVERE, null, ex);
            data_path.setText("empty");
        }
    }//GEN-LAST:event_jButton_browser_dataActionPerformed

    private void config_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_config_pathActionPerformed
        try {
            ready();
        } catch (Exception ex) {
            Logger.getLogger(CARSKit_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_config_pathActionPerformed

    private void jButton_browser_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browser_configActionPerformed
        // TODO add your handling code here:
        OpenFile f = new OpenFile();
        try {
            f.openFile();
            config_path.setText(f.path);
            ready();
        } catch (IOException ex) {
            Logger.getLogger(CARSKit_Form.class.getName()).log(Level.SEVERE, null, ex);
            config_path.setText("empty");
        } catch (Exception ex) {
            Logger.getLogger(CARSKit_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_browser_configActionPerformed
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonRunGlobalAVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunGlobalAVGActionPerformed
        // TODO add your handling code here:
        runAlgorithm("GlobalAVG");
    }//GEN-LAST:event_jButtonRunGlobalAVGActionPerformed

    private void jButtonRunUserAVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunUserAVGActionPerformed
        // TODO add your handling code here:
        runAlgorithm("UserAVG");
    }//GEN-LAST:event_jButtonRunUserAVGActionPerformed

    private void jButtonRunItemAVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunItemAVGActionPerformed
        // TODO add your handling code here:
        runAlgorithm("ItemAVG");
    }//GEN-LAST:event_jButtonRunItemAVGActionPerformed

    private void jButtonRunContextAVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunContextAVGActionPerformed
        // TODO add your handling code here:
        runAlgorithm("ContextAVG");
    }//GEN-LAST:event_jButtonRunContextAVGActionPerformed

    private void jButtonRunUserItemAVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunUserItemAVGActionPerformed
        // TODO add your handling code here:
        runAlgorithm("UserItemAVG");
    }//GEN-LAST:event_jButtonRunUserItemAVGActionPerformed

    private void jButtonRunUserContextAVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunUserContextAVGActionPerformed
        // TODO add your handling code here:
        runAlgorithm("RunUserContextAVG");
    }//GEN-LAST:event_jButtonRunUserContextAVGActionPerformed

    private void jButtonRunItemContextAVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunItemContextAVGActionPerformed
        // TODO add your handling code here:
        runAlgorithm("ItemContextAVG");
    }//GEN-LAST:event_jButtonRunItemContextAVGActionPerformed

    private void jButtonRunUserKNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunUserKNNActionPerformed
        // TODO add your handling code here:
        runAlgorithm("UserKNN");
    }//GEN-LAST:event_jButtonRunUserKNNActionPerformed

    private void jButtonRunItemKNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunItemKNNActionPerformed
        // TODO add your handling code here:
        runAlgorithm("ItemKNN");
    }//GEN-LAST:event_jButtonRunItemKNNActionPerformed

    private void jButtonRunSlopOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunSlopOneActionPerformed
        // TODO add your handling code here:
        runAlgorithm("SlopOne");
    }//GEN-LAST:event_jButtonRunSlopOneActionPerformed

    private void jButtonRunBiasedMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunBiasedMFActionPerformed
        // TODO add your handling code here:
        runAlgorithm("BiasedMF");
    }//GEN-LAST:event_jButtonRunBiasedMFActionPerformed

    private void jButtonRunPMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunPMFActionPerformed
        // TODO add your handling code here:
        runAlgorithm("PMF");
    }//GEN-LAST:event_jButtonRunPMFActionPerformed

    private void jButtonRunBPMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunBPMFActionPerformed
        // TODO add your handling code here:
        runAlgorithm("BPMF");
    }//GEN-LAST:event_jButtonRunBPMFActionPerformed

    private void jButtonRunNMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunNMFActionPerformed
        // TODO add your handling code here:
        runAlgorithm("NMF");
    }//GEN-LAST:event_jButtonRunNMFActionPerformed

    private void jButtonRunSVDPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunSVDPPActionPerformed
        // TODO add your handling code here:
        runAlgorithm("SVD++");
    }//GEN-LAST:event_jButtonRunSVDPPActionPerformed

    private void jButtonRunBPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunBPRActionPerformed
        // TODO add your handling code here:
        runAlgorithm("BPR");
    }//GEN-LAST:event_jButtonRunBPRActionPerformed

    private void jButtonRunSLIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunSLIMActionPerformed
        // TODO add your handling code here:
        runAlgorithm("SLIM");
    }//GEN-LAST:event_jButtonRunSLIMActionPerformed

    private void jButtonRunLRMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunLRMFActionPerformed
        // TODO add your handling code here:
        runAlgorithm("LRMF");
    }//GEN-LAST:event_jButtonRunLRMFActionPerformed

    private void jButtonRunRankALSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunRankALSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("RankALS");
    }//GEN-LAST:event_jButtonRunRankALSActionPerformed

    private void jButtonRunRankSGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunRankSGDActionPerformed
        // TODO add your handling code here:
        runAlgorithm("RankSGD");
    }//GEN-LAST:event_jButtonRunRankSGDActionPerformed

    private void jButtonRunUserSplittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunUserSplittingActionPerformed
        // TODO add your handling code here:
        runAlgorithm("UserSplitting");
    }//GEN-LAST:event_jButtonRunUserSplittingActionPerformed

    private void jButtonRunUISplittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunUISplittingActionPerformed
        // TODO add your handling code here:
        runAlgorithm("UISplitting");
    }//GEN-LAST:event_jButtonRunUISplittingActionPerformed

    private void jButtonRunItemSplittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunItemSplittingActionPerformed
        // TODO add your handling code here:
        runAlgorithm("ItemSplitting");
    }//GEN-LAST:event_jButtonRunItemSplittingActionPerformed

    private void jButtonRunTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunTFActionPerformed
        // TODO add your handling code here:
        runAlgorithm("CPTF");
    }//GEN-LAST:event_jButtonRunTFActionPerformed

    private void jButtonRunCAMF_MCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCAMF_MCSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCAMF_MCSActionPerformed

    private void jButtonRunCAMF_LCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCAMF_LCSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCAMF_LCSActionPerformed

    private void jButtonRunCAMF_ICSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCAMF_ICSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCAMF_ICSActionPerformed

    private void jButtonRunCAMF_CUCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCAMF_CUCIActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCAMF_CUCIActionPerformed

    private void jButtonRunCAMF_CUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCAMF_CUActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCAMF_CUActionPerformed

    private void jButtonRunCAMF_CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCAMF_CIActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCAMF_CIActionPerformed

    private void jButtonRunCAMF_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCAMF_CActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCAMF_CActionPerformed

    private void jButtonRunGCSLIM_CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunGCSLIM_CCActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunGCSLIM_CCActionPerformed

    private void jButtonRunCSLIM_CUCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCSLIM_CUCIActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCSLIM_CUCIActionPerformed

    private void jButtonRunCSLIM_ICSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCSLIM_ICSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCSLIM_ICSActionPerformed

    private void jButtonRunCSLIM_LCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCSLIM_LCSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCSLIM_LCSActionPerformed

    private void jButtonRunCSLIM_MCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCSLIM_MCSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCSLIM_MCSActionPerformed

    private void jButtonRunGCSLIM_ICSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunGCSLIM_ICSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunGCSLIM_ICSActionPerformed

    private void jButtonRunGCSLIM_LCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunGCSLIM_LCSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunGCSLIM_LCSActionPerformed

    private void jButtonRunGCSLIM_MCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunGCSLIM_MCSActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunGCSLIM_MCSActionPerformed

    private void jButtonRunCSLIM_CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCSLIM_CIActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCSLIM_CIActionPerformed

    private void jButtonRunCSLIM_CUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCSLIM_CUActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCSLIM_CUActionPerformed

    private void jButtonRunCSLIM_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCSLIM_CActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunCSLIM_CActionPerformed

    private void jButtonRunFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunFMActionPerformed
        // TODO add your handling code here:
        runAlgorithm("");
    }//GEN-LAST:event_jButtonRunFMActionPerformed

    public void show_data_table() throws FileNotFoundException, IOException {
        BufferedReader reader = new BufferedReader(new FileReader(data_path.getText()));
        String line;
        int line_number = 0;
        int MAX_LINES = 10;
        jTable_data.setModel(new DefaultTableModel());
        DefaultTableModel model = (DefaultTableModel)jTable_data.getModel();
//        model.getDataVector().removeAllElements();
//        model.fireTableDataChanged();
        
        line = reader.readLine();
        String[] header = line.trim().split(",");
        for(String column:header) {
        	Logs.debug("column : " + column);
            model.addColumn(column);
        }
        int row_length = header.length;
        while ((line = reader.readLine()) != null && line_number < MAX_LINES) {
        	line_number++;
        	
        	String[] row_content = line.trim().split(",");
        	Object[] row = new Object[row_length];
        	for (int i=0; i < row_length; i++)
        		row[i] = row_content[i];
        	model.addRow(row);

        	
        	
        	for (String value:row_content) {
        		System.out.print(value);
        	}
        	System.out.println("  " + line_number + " " + MAX_LINES);
        }
    }

    public void ready() throws Exception {
        kit = new CARS();
        kit.preset(config_path.getText());
        kit.readData();
        Logs.debug(kit.OriginalRatingDataPath);
        data_path.setText(kit.OriginalRatingDataPath);
//        Logs.debug(kit.rateDao.getHeader().toString());
        show_data_table();
    }

    public void runAlgorithm(String algo) {
        kit.algorithmChoosen = algo;
        try {
            kit.runAlgorithm();
        } catch (Exception ex) {
            Logger.getLogger(CARSKit_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CARSKit_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CARSKit_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CARSKit_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CARSKit_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CARSKit_Form form = new CARSKit_Form();
                form.setVisible(true);
                try {
                    form.ready();
                } catch (Exception ex) {
                    Logger.getLogger(CARSKit_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private static CARS kit;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField config_path;
    private javax.swing.JTextField data_path;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRunBPMF;
    private javax.swing.JButton jButtonRunBPR;
    private javax.swing.JButton jButtonRunBiasedMF;
    private javax.swing.JButton jButtonRunCAMF_C;
    private javax.swing.JButton jButtonRunCAMF_CI;
    private javax.swing.JButton jButtonRunCAMF_CU;
    private javax.swing.JButton jButtonRunCAMF_CUCI;
    private javax.swing.JButton jButtonRunCAMF_ICS;
    private javax.swing.JButton jButtonRunCAMF_LCS;
    private javax.swing.JButton jButtonRunCAMF_MCS;
    private javax.swing.JButton jButtonRunCSLIM_C;
    private javax.swing.JButton jButtonRunCSLIM_CI;
    private javax.swing.JButton jButtonRunCSLIM_CU;
    private javax.swing.JButton jButtonRunCSLIM_CUCI;
    private javax.swing.JButton jButtonRunCSLIM_ICS;
    private javax.swing.JButton jButtonRunCSLIM_LCS;
    private javax.swing.JButton jButtonRunCSLIM_MCS;
    private javax.swing.JButton jButtonRunContextAVG;
    private javax.swing.JButton jButtonRunFM;
    private javax.swing.JButton jButtonRunGCSLIM_CC;
    private javax.swing.JButton jButtonRunGCSLIM_ICS;
    private javax.swing.JButton jButtonRunGCSLIM_LCS;
    private javax.swing.JButton jButtonRunGCSLIM_MCS;
    private javax.swing.JButton jButtonRunGlobalAVG;
    private javax.swing.JButton jButtonRunItemAVG;
    private javax.swing.JButton jButtonRunItemContextAVG;
    private javax.swing.JButton jButtonRunItemKNN;
    private javax.swing.JButton jButtonRunItemSplitting;
    private javax.swing.JButton jButtonRunLRMF;
    private javax.swing.JButton jButtonRunNMF;
    private javax.swing.JButton jButtonRunPMF;
    private javax.swing.JButton jButtonRunRankALS;
    private javax.swing.JButton jButtonRunRankSGD;
    private javax.swing.JButton jButtonRunSLIM;
    private javax.swing.JButton jButtonRunSVDPP;
    private javax.swing.JButton jButtonRunSlopOne;
    private javax.swing.JButton jButtonRunTF;
    private javax.swing.JButton jButtonRunUISplitting;
    private javax.swing.JButton jButtonRunUserAVG;
    private javax.swing.JButton jButtonRunUserContextAVG;
    private javax.swing.JButton jButtonRunUserItemAVG;
    private javax.swing.JButton jButtonRunUserKNN;
    private javax.swing.JButton jButtonRunUserSplitting;
    private javax.swing.JButton jButton_browser_config;
    private javax.swing.JButton jButton_browser_data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAlgorithm;
    private javax.swing.JPanel jPanelConfig;
    private javax.swing.JPanel jPanelVariable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedChoossen;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JTable jTable_data;
    // End of variables declaration//GEN-END:variables
}
